version: '3.7'
services:
  web:
    container_name: "stellot-keybase-auth-dev"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    command: npm run start:dev
    ports:
      - $PORT:8080
    volumes:
      - .:/server
    restart: 'unless-stopped'
