version: '3.1'
services:
  web:
    container_name: "stellot-keybase-auth"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "${PORT}:${PORT}"
    restart: 'unless-stopped'
