version: '3.7'
services:
  ipfs-node:
    container_name: "stellot-ipfs-node"
    image: ipfs/go-ipfs
    ports: # https://github.com/ipfs/go-ipfs/blob/master/Dockerfile#L74 
      - "4001:4001"
      - "5001"
      - "8080"
      - "8081"
    networks:
      - public
    labels:
      - "traefik.http.routers.ipfs-node.rule=Host(`ipfs.stellot.com`)"
      - "traefik.http.services.ipfs-node.loadbalancer.server.port=8080"
      - "traefik.enable=true"

  mongo:
    container_name: "stellot-tds-mongodb"
    image: mongo:latest
    restart: 'unless-stopped'
    networks:
      - public

  tds:
    container_name: "stellot-tds"
    build:
      context: tds
      dockerfile: Dockerfile
    env_file: ./tds/.env
    ports:
      - "80"
    restart: 'unless-stopped'
    environment:
      - KEYBASE_AUTH_SERVER_URL=http://keybase-auth
      - EMAILS_AUTH_SERVER_URL=http://emails-auth
      - IPFS_NODE_URL=http://ipfs-node:5001
    links:
      - mongo
      - emails-auth
      - ipfs-node
    depends_on:
      - mongo
      - emails-auth
      - ipfs-node
    networks:
      - public
    labels:
      - "traefik.http.routers.tds.rule=Host(`tds.stellot.com`)"
      - "traefik.enable=true"

  emails-auth:
    container_name: "stellot-emails-auth"
    build:
      context: emails-auth
      dockerfile: Dockerfile
    env_file: ./emails-auth/.env
    restart: 'unless-stopped'
    ports:
      - "80"
    networks:
      - public
    labels:
      - "traefik.http.routers.emails-auth.rule=Host(`emails.stellot.com`)"
      - "traefik.enable=true"


networks:
  public:
    external: true
