version: '3.7'
services:
  nginx:
    container_name: "stellot-nginx"
    build: ./nginx
    image: nginx
    restart: 'unless-stopped'
    volumes:
      - $WEBAPP_DIR:/usr/share/nginx/html:ro
    ports:
      - $NGINX_PORT:80
    
  mongo:
    container_name: "stellot-tds-mongodb-dev"
    image: mongo:latest
    restart: 'unless-stopped'
    volumes:
      - $DOCKER_VOLUMES/stellot-tds-dev:/data/db

  tds:
    container_name: "stellot-tds-dev"
    build:
      context: server
      dockerfile: Dockerfile
    env_file: ./server/.env
    command: npm run start:dev
    ports:
      - $TDS_PORT:8080
    volumes:
      - $WEBAPP_DIR:$WEBAPP_DIR
      - ./server:/server
    restart: 'unless-stopped'
    environment:
      - KEYBASE_AUTH_SERVER_URL=http://keybase-auth:$KEYBASE_AS_PORT
      - EMAILS_AUTH_SERVER_URL=http://emails-auth:$EMAILS_AS_PORT
    links:
      - mongo
      - keybase-auth
      - emails-auth
    depends_on:
      - mongo
      - keybase-auth
      - emails-auth

  keybase-auth:
    container_name: "stellot-keybase-auth-dev"
    build:
      context: keybase-auth
      dockerfile: Dockerfile
    env_file: ./keybase-auth/.env
    command: npm run start:dev
    ports:
      - $KEYBASE_AS_PORT:8080
    restart: 'unless-stopped'

  emails-auth:
    container_name: "stellot-emails-auth-dev"
    build:
      context: emails-auth
      dockerfile: Dockerfile
    env_file: ./emails-auth/.env
    command: npm run start:dev
    volumes:
      - ./emails-auth:/server
    ports:
      - $EMAILS_AS_PORT:8080
    restart: 'unless-stopped'

