version: '3.7'
services:
  ipfs-node:
    container_name: "stellot-ipfs-node"
    image: ipfs/go-ipfs
    ports: # https://github.com/ipfs/go-ipfs/blob/master/Dockerfile#L74 
      - "4001:4001"
      - "5001"
      - "8080"
      - "8081"
    networks:
      - public
      - default

  mongo:
    container_name: "stellot-tds-mongodb"
    image: mongo:latest
    restart: 'unless-stopped'
    networks:
      - public
      - default

  tds:
    container_name: "stellot-tds"
    build:
      context: tds
      dockerfile: Dockerfile
    env_file: ./tds/.env
    restart: 'unless-stopped'
    environment:
      - KEYBASE_AUTH_SERVER_URL=http://keybase-auth
      - EMAILS_AUTH_SERVER_URL=http://emails-auth
      - IPFS_NODE_URL=http://ipfs-node:5001
    links:
      - mongo
      - emails-auth
      - ipfs-node
    depends_on:
      - mongo
      - emails-auth
      - ipfs-node
    networks:
      - public
      - default

  emails-auth:
    container_name: "stellot-emails-auth"
    build:
      context: emails-auth
      dockerfile: Dockerfile
    env_file: ./emails-auth/.env
    restart: 'unless-stopped'
    networks:
      - public
      - default


networks:
  public:
    external: true
