version: '3.7'
services:
  mongo:
    container_name: "stellot-tds-mongodb"
    image: mongo:latest
    restart: 'unless-stopped'
    volumes:
      - $DOCKER_VOLUMES/stellot-tds:/data/db

  tds:
    container_name: "stellot-tds"
    build:
      context: server
      dockerfile: Dockerfile
    env_file: ./server/.env
    ports:
      - $TDS_PORT:8080
    volumes:
      - $WEBAPP_DIR:$WEBAPP_DIR
    restart: 'unless-stopped'
    environment:
      - KEYBASE_AUTH_SERVER_URL=http://keybase-auth:$KEYBASE_AS_PORT
    links:
      - mongo
      - keybase-auth
    depends_on:
      - mongo
      - keybase-auth

  keybase-auth:
    container_name: "stellot-keybase-auth"
    build:
      context: keybase-auth
      dockerfile: Dockerfile
    env_file: ./keybase-auth/.env
    ports:
      - $KEYBASE_AS_PORT:8080
    restart: 'unless-stopped'

