version: '3.7'
services:
  mongo:
    container_name: "stellot-tds-mongodb-dev"
    image: mongo:latest
    restart: 'unless-stopped'
    ports:
      - 27017:27017
    volumes:
      - $DOCKER_VOLUMES/stellot-tds:/data/db

  tds:
    container_name: "stellot-tds-dev"
    build:
      context: server
      dockerfile: Dockerfile.dev
    env_file: ./server/.env
    ports:
      - $TDS_PORT:$TDS_PORT
    volumes:
      - "${WEBAPP_DIR}:${WEBAPP_DIR}"
    restart: 'unless-stopped'
    environment:
      - KEYBASE_AUTH_SERVER_URL=http://keybase-auth:$KEYBASE_AS_PORT
    links:
      - mongo
      - keybase-auth
    depends_on:
      - mongo
      - keybase-auth

  keybase-auth:
    container_name: "stellot-keybase-auth-dev"
    build:
      context: keybase-auth
      dockerfile: Dockerfile.dev
    env_file:
      - ./keybase-auth/.env
    ports:
      - $KEYBASE_AS_PORT:$KEYBASE_AS_PORT
    restart: 'unless-stopped'

