version: '3.7'
services:
  web:
    container_name: "stellot-keybase-auth"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - $PORT:8080
    restart: 'unless-stopped'
