version: '2'
services:
  web:
    container_name: "stellar-voting-authorization-server"
    build: .
    env_file: ".env"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "${WEBAPP_DIR}:${WEBAPP_DIR}"
    restart: 'unless-stopped'
