version: '3.7'
services:
  website:
    image: nginx
    ports:
      - $PORT:80
    volumes:
      - ../docs:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped